site_name: System Design Observation
site_description: Notes and examples on System Design, OOP, and Design Patterns
site_author: Raj Gupta
repo_url: https://github.com/Raj-G07/System-design-observation
repo_name: ""
plugins:
  - search
  - mermaid2
theme:
  name: material
  icon:
    repo: fontawesome/brands/github   # âœ… GitHub logo only
  font:
    text: Inter
    code: Fira Code
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - content.code.copy
    - search.suggest
    - search.highlight
  palette:
    # Light Mode
    - scheme: default
      primary: indigo
      accent: deep-purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark Mode
    - scheme: slate
      primary: deep-purple
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - 01. System Design vs DSA: 01 . system-design-vs-dsa.md
  - 02. Pillars of System Design: 02 . pillars-of-system-design.md
  - 03. HLD vs LLD: 03 . hld-vs-lld.md
  - 04. OOPs in System Design: 04 . oops-in-system-design.md
  - 05. UML Diagrams: 05 . uml-diagrams.md
  - 06. Class Diagrams: 06 . class-diagrams.md
  - 07. Sequence Diagrams: 07 . sequence-diagrams.md
  - 08. SOLID Principles: 08 . solid-design-principles.md
  - 09. Signature/Property/Method Rule: 09 . signature-property-method-rule.md
  - 10. Exception Rule: 10 . exception-rule.md
  - 11. Real World Example: 11 . real-world-example.md
  - 12. Strategy Pattern: 12 . strategy-design-pattern.md
  - 13. Factory Pattern: 13 . factory-design-pattern.md
  - 14. Singleton Pattern: 14 . singleton-design-pattern.md
  - 15. Food Delivery System Design: 15 . food-delivery-app-design.md
  - 16. Observer Pattern: 16 . observer-design-pattern.md 
  - 17. Decorator Pattern: 17 . decorator-design-pattern.md
  - 18. Notification System Design: 18 . notification-system-design.md
  - 19. Command Pattern: 19 . command-design-pattern.md
  - 20. Adapter Pattern: 20 . adapter-design-pattern.md
  - 21. Facade Pattern: 21 . facade-design-pattern.md
  - 22. Law of Demeter: 22 . law-of-demeter.md
  - 23. Music Player System Design: 23 . music-player-design.md
  - 24. Composite Pattern: 24 . composite-design-pattern.md
  - 25. Template Pattern: 25 . template-method-pattern.md
  - 26. Proxy Pattern: 26 . proxy-design-pattern.md
  - 27. Chain of Responsibility: 27 . chain-of-responsibility.md
  - 28. Payment Gateway System Design: 28 . payment-gateway-system.md
  - 29. Discout Coupon Design: 29 . discount-coupon-design.md
  - 30. Bridge Pattern: 30 . bridge-pattern.md 
  - 31. Inventory Management System Design: 31 . inventory-management.md
  
markdown_extensions:
  # --- Core extensions ---
  - admonition
  - toc:
      permalink: true
  - tables
  - fenced_code
  - codehilite:
      guess_lang: false
      linenums: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums_style: inline
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tasklist      # Task lists
extra_css:
  - styles/mermaid-custom.css
  - styles/custom.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js
  - js/mermaid-init.js
